---
spring:
  profiles:
    active: local


  datasource:
    url: jdbc:mysql://localhost:3306/slogday
    username: root
    password: root
    #driverClassName: com.mysql.jdbc.Driver

server:
  port: 8086